@startuml curriculum
allowmixing
hide circle
skinparam linetype ortho

left to right direction

package DomainModel {
 
 
    package タグ集約 #LightPink
    {
        card タグ[
            タグ
            --
            ID
            タグ名
        ]
    }
        
    package カテゴリ集約 #LightSalmon
    {
        card カテゴリ[
            カテゴリ
            --
            ID
            カテゴリ名
        ]
    }
        note right of カテゴリ 
        プログラミング
        マーケティング
        デザイン
        ライティング
        動画・映像
        ビジネス
        語学
        ライフスタイル
        end note

    package 契約集約 #LightSteelBlue
    {
        card 契約[
            契約
            --
            ID
            契約リクエストID
            承認メッセージ
        ]

        note left of 契約
        月額契約は２か月目以降は契約時の金額を請求する
            ==
            例えば１か月目に１万円で契約したが２か月目はプランが２万円に変わっていた場合
            引き続き１万円で契約は続行する
            --
            ２万円に変わってから契約した人は２万円の月額契約となる
            --
            承認メッセージは最大５００文字
        end note
    }

    package 提案集約 #LightGoldenRodYellow
    {
        card 提案[
            提案
            --
            ID
            ユーザーID
            メンター募集ID
            提案内容
        ]
        note left of 提案
            提案内容
            --
            提案内容: 2000文字以内
            提案できるのはスキルを５個以上持つユーザーのみ
        end note
    }

    package ユーザー集約 #lightblue
    {
        card ユーザー[
            ユーザー
            --
            ID
            名前
            メールアドレス
            パスワード
            List<スキル>
            プロファイル
            List<経歴>
        ]

        card スキル[
            スキル
            --
            ID
            タグID
            評価
            年数
        ]

        card 経歴 [
            経歴
            --
            ID
            詳細
            西暦from
            西暦to
        ]

    ユーザー "1.." o-- "0..*" 経歴
        ユーザー "1.." o-- "0..*" スキル
        タグ "0.." --o "0*" スキル
        
        note left of ユーザー 
            必須項目
            ==
            名前：２５５文字以内(ユニーク)
            メールアドレス : ２５５文字以内
            --
            パスワード : １２文字以上　英数字それぞれ１文字以上

        end note

        note left of 経歴
            経歴：
                        詳細    ：1000字以内
                        西暦from：1970年以上のint型
                        西暦to  ：1970年以上のint型、西暦fromよりも大きい数字
        end note

        note left of スキル
        スキル：
                ①　タグ名（選択式）
                ②　評価（1~5）
                ③　１つ以上
                ④　年数　0以上のint型　(5年まで)
        end note
    }

    package メンター募集集約 #LimeGreen
    {
        card メンター募集[
            メンター募集
            --
            ID
            タイトル
            タグID
            カテゴリID
            予算from
            予算to
            提案数
            応募期間from
            応募期間to
            相談形式
            相談方式
            ディスクリプション
            ステータス
        ]
        
        メンター募集 "1" o-- "0*" タグ
        メンター募集 "1" o-- "1*" カテゴリ
        メンター募集 "1" o-- "0..*" 提案
        提案 "0.." --o "1*" ユーザー

        note left of メンター募集
            メンター募集
            --
            ページネーション 20件
            --
            任意項目
            --
            タグは複数OK
            --
            予算は１０００円以上の数値
            --
            相談形式： 単発or継続
            相談方式： チャットorビデオ通話
            --
            ディスクリプション2000字
            --
            ステータス：公開or中止
        end note 

    }

    package プラン集約 #LightSkyBlue
    {
        card プラン[
            プラン
            --
            ID
            タイトル
            カテゴリID
            タグID
            内容
            ステータス
            相談形式
            相談方式
            契約ID
            ユーザーID   
        ]

        プラン "0" o-- "0*" タグ
        プラン "0" o-- "0*" カテゴリ
        プラン "0" o-- "0*" 契約
        プラン "0" o-- "1*" ユーザー

        note left of プラン
            プラン 
            --
            タイトル：２５５文字以内
            タグ：５個まで
            ステータス：公開or中止　ステータスが中止となっていないものだけ表示する
            ページネーション20件

            任意項目
            ==
            相談方式
            チャットorビデオ通話
            ==
            相談形式： 単発or継続
        end note
    }
    package 契約リクエスト集約 #LightGreen
    {
        card 契約リクエスト[
            契約リクエスト
            --
            ID
            メッセージ
            プランID
            契約金額
        ]
        契約リクエスト "0..*" o-- "0..*" プラン
        契約リクエスト "0..*" o-- "0..*" 契約 
        note left of 契約リクエスト
        リクエストメッセージは最大５００文字
        end note
    }
}

@enduml